### ISSUE TITLE
Marking watched episodes throws an error

### ISSUE THREAD

**Issue by ZeusLT** [saleek-pa/Movie-API#2]
When marking episodes as watched one by one I get an error:

```
ERROR
Cannot add property 623, object is not extensible
TypeError: Cannot add property 623, object is not extensible
    at Array.push (<anonymous>)
    at handleEpisodeCheckbox (http://localhost:3000/static/js/bundle.js:4113:24)
    at http://localhost:3000/static/js/bundle.js:60942:20
    at Immer2.produce (http://localhost:3000/static/js/bundle.js:62946:20)
    at http://localhost:3000/static/js/bundle.js:60941:64
    at Array.reduce (<anonymous>)
    at reducer (http://localhost:3000/static/js/bundle.js:60922:25)
    at reducer (http://localhost:3000/static/js/bundle.js:61351:16)
    at combination (http://localhost:3000/static/js/bundle.js:72282:31)
    at Object.dispatch (http://localhost:3000/static/js/bundle.js:72129:22)
ERROR
Cannot add property 623, object is not extensible
TypeError: Cannot add property 623, object is not extensible
    at Array.push (<anonymous>)
    at handleEpisodeCheckbox (http://localhost:3000/static/js/bundle.js:4113:24)
    at http://localhost:3000/static/js/bundle.js:60942:20
    at Immer2.produce (http://localhost:3000/static/js/bundle.js:62946:20)
    at http://localhost:3000/static/js/bundle.js:60941:64
    at Array.reduce (<anonymous>)
    at reducer (http://localhost:3000/static/js/bundle.js:60922:25)
    at reducer (http://localhost:3000/static/js/bundle.js:61351:16)
    at combination (http://localhost:3000/static/js/bundle.js:72282:31)
    at Object.dispatch (http://localhost:3000/static/js/bundle.js:72129:22)
ERROR
Cannot add property 623, object is not extensible
TypeError: Cannot add property 623, object is not extensible
    at Array.push (<anonymous>)
    at handleEpisodeCheckbox (http://localhost:3000/static/js/bundle.js:4113:24)
    at http://localhost:3000/static/js/bundle.js:60942:20
    at Immer2.produce (http://localhost:3000/static/js/bundle.js:62946:20)
    at http://localhost:3000/static/js/bundle.js:60941:64
    at Array.reduce (<anonymous>)
    at reducer (http://localhost:3000/static/js/bundle.js:60922:25)
    at reducer (http://localhost:3000/static/js/bundle.js:61351:16)
    at combination (http://localhost:3000/static/js/bundle.js:72282:31)
    at Object.dispatch (http://localhost:3000/static/js/bundle.js:72129:22)
```

![image](https://github.com/saleek-pa/Movie-API/assets/22300013/607794e6-9d2c-4b46-a222-8b280595cb8b)

If I mark the whole season as completed and then unmark it, then I can mark episodes one by one without an error.  

Here is gif demonstration: 
![explaination](https://github.com/saleek-pa/Movie-API/assets/22300013/c403bb32-8f00-4483-9a32-81582208660e)

**Comment by saleek-pa** [comment]
Thanks for reporting this and providing such clear visuals! The issue with marking episodes individually has been fixed. You can now mark them without any errors. If you encounter any more issues or have further feedback, feel free to reach out. Your detailed report was super helpful! 🙌
